// Original, hand-written starter questions for Verbal Reasoning (VRB) and the
// deductive / relations parts of Logical Reasoning (REA). Written for this
// platform (workplace and everyday Indian contexts) - not copied from any
// exam paper. Each wrong option carries the reason it is wrong.

const q = (skillId, level, prompt, answer, wrong, explanation, hint) => ({
  skillId,
  level,
  prompt,
  correctAnswer: answer,
  options: [answer, ...Object.keys(wrong)],
  distractorReasons: wrong,
  explanation,
  hint,
  timeLimitSeconds: 75 + level * 15,
});

const TFCS_WRONG = {
  True: "The passage doesn't state or directly imply this.",
  False: "Nothing in the passage contradicts this.",
  "Cannot say": "The passage does settle this - reread it.",
};
const tfcs = (level, passage, statement, answer, explanation) =>
  q(
    "VRB.PAS.TFCS",
    level,
    `Read the passage, then decide whether the statement is True, False, or Cannot say from the passage alone.\n\nPassage: ${passage}\n\nStatement: ${statement}`,
    answer,
    Object.fromEntries(Object.entries(TFCS_WRONG).filter(([k]) => k !== answer)),
    explanation,
    "Use only what the passage says - not what you know or assume."
  );

export const AUTHORED_QUESTIONS = [
  // --------------------------------------------- VRB: True / False / Cannot say
  tfcs(2,
    "The support centre in Pune opened in 2019 with 40 agents. It now employs 160 agents across three shifts, and handles calls for two banking clients.",
    "The Pune support centre has four times as many agents as when it opened.",
    "True",
    "40 agents at opening, 160 now: 160 ÷ 40 = 4."),
  tfcs(3,
    "The support centre in Pune opened in 2019 with 40 agents. It now employs 160 agents across three shifts, and handles calls for two banking clients.",
    "Each shift at the Pune centre has the same number of agents.",
    "Cannot say",
    "The passage gives the total and the number of shifts, but not how agents are split between shifts."),
  tfcs(3,
    "All new hires complete a two-week product training before taking live calls. Priya joined last Monday and has not finished her training yet.",
    "Priya took live calls last week.",
    "False",
    "She joined last Monday and hasn't finished the two-week training, and new hires only take live calls after training."),
  tfcs(4,
    "Customer satisfaction scores rose from 78% to 86% in the quarter after the company introduced a callback option. During the same quarter, average waiting time fell by two minutes.",
    "The callback option caused the rise in customer satisfaction.",
    "Cannot say",
    "Both changes happened together; the passage doesn't say which one (if either) caused the rise."),

  // ------------------------------------------------ VRB: Sentence completion
  q("VRB.SCP.COMPLETE", 2,
    "Choose the word that best completes the sentence:\n\"The manager was ______ with the report because it was finished two days early and had no errors.\"",
    "delighted",
    { furious: "The report was early and error-free, so anger doesn't fit.", indifferent: "'Because' signals a reason for a clear reaction, not a lack of one.", confused: "Nothing in the sentence suggests the report was unclear." },
    "An early, error-free report is a reason to be pleased, so 'delighted' fits.",
    "Look for the clue that explains the feeling."),
  q("VRB.SCP.COMPLETE", 3,
    "Choose the word that best completes the sentence:\n\"Although the new process seemed complicated at first, the team soon found it surprisingly ______.\"",
    "straightforward",
    { complex: "'Although' sets up a contrast, so the word must be the opposite of 'complicated'.", tedious: "Doesn't contrast with 'complicated' - it adds another negative.", expensive: "Cost isn't what the sentence is contrasting." },
    "'Although ... complicated' needs a contrasting word: 'straightforward'.",
    "'Although' signals a contrast."),
  q("VRB.SCP.COMPLETE", 3,
    "Choose the pair that best completes the sentence:\n\"The customer's complaint was ______, so the agent ______ a full refund immediately.\"",
    "justified ... approved",
    { "baseless ... approved": "A baseless complaint wouldn't lead to an immediate full refund.", "justified ... refused": "A justified complaint makes refusing the refund illogical.", "unclear ... processed": "An unclear complaint wouldn't be settled immediately with a full refund." },
    "A justified complaint logically leads to the refund being approved - 'so' links cause and effect.",
    "Both blanks must fit the cause-and-effect link 'so'."),
  q("VRB.SCP.COMPLETE", 4,
    "Choose the word that best completes the sentence:\n\"Her explanation was so ______ that even customers with no technical knowledge understood it at once.\"",
    "lucid",
    { verbose: "Verbose means wordy - that usually makes things harder to follow.", cryptic: "Cryptic means hard to understand - the opposite of what happened.", technical: "A technical explanation would be hard for non-technical customers." },
    "'Lucid' means clear and easy to understand, which is why everyone understood it.",
    "The result ('understood it at once') tells you the quality."),
  q("VRB.SCP.COMPLETE", 5,
    "Choose the word that best completes the sentence:\n\"Rather than resolving the dispute, the new policy only served to ______ the tension between the two departments.\"",
    "exacerbate",
    { alleviate: "'Rather than resolving' means things got worse, not better.", conceal: "Hiding tension isn't the opposite of resolving it in this sentence.", justify: "Doesn't describe what happened to the tension." },
    "'Rather than resolving' signals the opposite result - the tension got worse: 'exacerbate'.",
    "'Rather than' tells you the result was the opposite of resolving."),

  // ------------------------------------------------- VRB: Sentence ordering
  q("VRB.PJM.ORDER", 3,
    "Arrange the sentences in the most logical order:\nP: Then, confirm the customer's identity using two security questions.\nQ: First, greet the customer and give your name.\nR: Finally, summarise the solution and ask if there is anything else.\nS: Next, listen to the problem without interrupting.",
    "QPSR",
    { QSPR: "Identity is checked before discussing the account problem in detail.", PQSR: "The greeting must come first ('First').", QPRS: "'Finally' (R) must be the last step." },
    "Q (First) → P (Then) → S (Next) → R (Finally).",
    "Look for sequence words: First, Then, Next, Finally."),
  q("VRB.PJM.ORDER", 4,
    "Arrange the sentences in the most logical order:\nP: As a result, many customers abandoned their calls before reaching an agent.\nQ: Last year, the company replaced its phone menu with a longer, eight-option version.\nR: The menu was shortened again, and abandoned calls fell by half.\nS: Callers found it confusing and took several minutes to reach the right team.",
    "QSPR",
    { QPSR: "P says 'As a result' - it needs a cause before it (S).", SQPR: "S describes a problem with 'it' - the menu must be introduced first (Q).", QSRP: "R (the fix) must come after the effect it fixed (P)." },
    "Q introduces the menu → S the problem → P its result → R the fix.",
    "Find the opening sentence that introduces the topic, then follow cause → effect."),
  q("VRB.PJM.ORDER", 4,
    "Arrange the sentences in the most logical order:\nP: However, it also needs to be updated whenever a product changes.\nQ: A good knowledge base saves agents time on every call.\nR: Otherwise, agents end up giving customers outdated information.\nS: They can find answers in seconds instead of asking a supervisor.",
    "QSPR",
    { QPSR: "S explains the benefit in Q, so it follows Q directly.", SQPR: "'They' in S needs 'agents' from Q first.", QSRP: "'Otherwise' (R) refers back to the need for updates in P." },
    "Q (claim) → S (benefit explained) → P (however, a condition) → R (otherwise, the risk).",
    "Pronouns (they) and linking words (however, otherwise) show what must come before."),
  q("VRB.PJM.ORDER", 5,
    "Arrange the sentences in the most logical order:\nP: This data is then reviewed weekly by team leaders.\nQ: Every call is tagged with a reason code by the agent.\nR: Recurring issues are sent to the product team to fix at the source.\nS: They look for issues that appear again and again.",
    "QPSR",
    { QSPR: "'They' in S refers to the team leaders introduced in P.", PQSR: "'This data' in P refers to the tagged calls in Q.", QPRS: "R acts on the recurring issues found in S, so S comes first." },
    "Q (tag calls) → P (this data reviewed by team leaders) → S (they look for patterns) → R (recurring issues fixed).",
    "Follow the references: 'This data', 'They'."),

  // ------------------------------------------------- VRB: Critical reasoning
  q("VRB.CRT.STRENGTHEN", 3,
    "Argument: \"Agents who complete the new empathy training resolve complaints faster, so the training should be given to every agent.\"\nWhich statement, if true, most STRENGTHENS this argument?",
    "Agents who took the training had similar resolution times to others before the training.",
    { "The training takes two full days to complete.": "The time cost is irrelevant to whether the training works - if anything it weakens the case.", "Only the most experienced agents volunteered for the training.": "This weakens it: experience, not training, may explain the faster times.", "Some customers prefer to speak to senior agents.": "Unrelated to whether the training improves resolution speed." },
    "If trained and untrained agents started out equal, the improvement is more likely caused by the training.",
    "Look for the option that rules out another explanation."),
  q("VRB.CRT.STRENGTHEN", 4,
    "Argument: \"Our Chennai team has the highest customer ratings, so their call scripts should be used by every team.\"\nWhich statement, if true, most WEAKENS this argument?",
    "The Chennai team handles only simple account queries, while other teams handle complex complaints.",
    { "The Chennai team's scripts were written last year.": "The age of the scripts doesn't show they don't work.", "The Chennai team is the largest team in the company.": "Team size doesn't explain away the higher ratings.", "Customers rated the Chennai team highly for three months in a row.": "This supports the argument rather than weakening it." },
    "If Chennai gets easier calls, the high ratings may come from the call type, not the scripts.",
    "Weaken = give another reason for the result."),
  q("VRB.CRT.ASSUMPTION", 3,
    "Argument: \"Ravi has a strong accent, so customers will not understand him on calls.\"\nWhich assumption does this argument depend on?",
    "A strong accent always makes speech hard for customers to understand.",
    { "Ravi does not want to work on calls.": "His preferences aren't part of the reasoning.", "Customers prefer agents from their own city.": "The argument is about understanding, not preference.", "Ravi speaks too quickly on calls.": "Speed isn't mentioned - the argument relies only on accent." },
    "The conclusion only follows if an accent necessarily blocks understanding - an unstated (and questionable) assumption.",
    "What must be true for the conclusion to follow?"),
  q("VRB.CRT.ASSUMPTION", 4,
    "Argument: \"We should move our support team to a night shift, because most of our customers are in the United States.\"\nWhich assumption does this argument depend on?",
    "US customers mostly contact support during their own daytime hours.",
    { "Night shifts are more expensive to run.": "This is a reason against the plan, not an assumption it relies on.", "Agents prefer working at night.": "The argument is based on customers, not agent preference.", "The company has no customers in India.": "The argument says 'most', so it doesn't need there to be none." },
    "The night-shift plan only makes sense if US customers call during their daytime, which is India's night.",
    "Ask: what link between the reason and the conclusion is taken for granted?"),
  q("VRB.CRT.INFERENCE", 3,
    "Statement: \"Every agent who meets the quality target this month gets a bonus. Meena did not get a bonus this month.\"\nWhich conclusion MUST be true?",
    "Meena did not meet the quality target this month.",
    { "Meena's quality score was the lowest in the team.": "She missed the target, but we can't tell by how much.", "Meena will not get a bonus next month.": "The statement is only about this month.", "Only agents who meet the target get a bonus.": "The rule says meeting the target is enough for a bonus, not that it's the only way." },
    "Meeting the target guarantees a bonus. No bonus → she can't have met the target.",
    "If A always leads to B, then 'no B' means 'no A'."),
  q("VRB.CRT.INFERENCE", 4,
    "Statement: \"Some team leaders are certified trainers. All certified trainers have at least five years' experience.\"\nWhich conclusion MUST be true?",
    "Some team leaders have at least five years' experience.",
    { "All team leaders have at least five years' experience.": "Only SOME team leaders are certified trainers.", "All experienced staff are team leaders.": "Nothing links all experienced staff to being team leaders.", "No team leader has less than five years' experience.": "The team leaders who aren't trainers could have less experience." },
    "The team leaders who are certified trainers must have five or more years, so at least some team leaders do.",
    "Draw two overlapping circles."),
  q("VRB.CRT.FLAW", 4,
    "Argument: \"Last month, two customers complained about our new app. So the new app is a failure.\"\nWhat is the main flaw in this argument?",
    "It draws a general conclusion from too few cases.",
    { "It assumes the customers were wrong.": "The argument actually trusts the customers' complaints.", "It confuses the app with the website.": "The website isn't mentioned.", "It relies on the opinion of an expert.": "No expert is quoted." },
    "Two complaints out of possibly thousands of users isn't enough to call the whole app a failure.",
    "Ask: is the evidence enough for such a big conclusion?"),
  q("VRB.CRT.FLAW", 5,
    "Argument: \"Since we started playing music in the office, sales have gone up. Music clearly makes our team sell more.\"\nWhat is the main flaw in this argument?",
    "It assumes that because one thing followed another, the first caused the second.",
    { "It uses too small a sample of teams.": "Possible, but the central error is treating timing as proof of cause.", "It attacks the people rather than the idea.": "No one is attacked.", "It relies on the opinion of the sales team.": "The argument uses sales figures, not opinions." },
    "Sales may have risen for other reasons (season, new product, pricing). Happening after isn't proof of caused by.",
    "Could anything else explain the rise?"),

  // ------------------------------------------------ VRB: Fact vs opinion / evaluate
  q("VRB.ARG.FACTOPINION", 2,
    "Which of these statements is a FACT rather than an opinion?",
    "The office opens at 9 a.m. on weekdays.",
    { "Our office has the friendliest staff in the city.": "'Friendliest' is a judgement - an opinion.", "Working from the office is better than working from home.": "'Better' is a judgement that people may disagree on.", "The new canteen menu is delicious.": "'Delicious' is a personal taste - an opinion." },
    "Opening hours can be checked and proved; the others are judgements.",
    "A fact can be checked; an opinion is a judgement."),
  q("VRB.ARG.FACTOPINION", 2,
    "Which of these statements is an OPINION rather than a fact?",
    "The new headsets are far more comfortable than the old ones.",
    { "The new headsets weigh 180 grams.": "Weight can be measured - a fact.", "The company bought 200 new headsets in March.": "Purchase records can confirm this - a fact.", "The new headsets have noise cancellation.": "A product feature that can be checked - a fact." },
    "Comfort is a personal judgement, so it's an opinion.",
    "Words like 'better', 'more comfortable', 'best' usually signal opinions."),
  q("VRB.ARG.FACTOPINION", 3,
    "\"Our average handling time fell to 5 minutes in June, which shows the team is finally working properly.\"\nWhich part of this sentence is an opinion?",
    "that the team is finally working properly",
    { "that average handling time fell": "This can be checked from call records.", "that the time was 5 minutes": "A measured figure - a fact.", "that this happened in June": "A date that can be checked - a fact." },
    "The figure and date are facts; 'finally working properly' is the speaker's judgement.",
    "Separate the measurable part from the judgement."),
  q("VRB.ARG.EVALUATE", 4,
    "Should all customer calls be recorded?\nArgument: \"Yes - recordings help trainers show agents real examples of good and poor calls.\"\nIs this a strong or weak argument?",
    "Strong - it gives a relevant, practical benefit directly linked to the question.",
    { "Weak - it doesn't mention cost.": "An argument can be strong without covering every point.", "Weak - trainers can use made-up examples instead.": "That's a counter-argument, not a flaw in this one.", "Strong - because most companies already do it.": "That isn't the reason given, and 'everyone does it' is a weak reason anyway." },
    "A strong argument gives an important, relevant reason directly related to the question - this one does.",
    "Strong = relevant and important; weak = trivial, unrelated, or just opinion."),
  q("VRB.ARG.EVALUATE", 4,
    "Should the company stop hiring freshers?\nArgument: \"Yes - one fresher we hired last year left after two months.\"\nIs this a strong or weak argument?",
    "Weak - it generalises from a single case.",
    { "Strong - freshers need a lot of training.": "That's a different reason from the one given.", "Strong - it's based on a real example.": "One real example isn't enough to decide a hiring policy.", "Weak - freshers are cheaper to hire.": "That's a counter-argument, not the reason this argument is weak." },
    "One person leaving doesn't justify a company-wide policy.",
    "Is the reason enough to support such a big decision?"),

  // ------------------------------------------------ REA: Syllogisms
  q("REA.DED.SYL", 2,
    "Statements: All agents are employees. All employees get an ID card.\nConclusion: All agents get an ID card.\nDoes the conclusion follow?",
    "Yes, it definitely follows",
    { "No, it does not follow": "Agents are inside employees, and all employees get a card - so agents do too.", "It follows only for some agents": "'All agents are employees' covers every agent.", "Cannot be decided": "The two 'all' statements settle it." },
    "Agents ⊂ employees ⊂ ID-card holders, so every agent gets an ID card.",
    "Draw circles inside circles."),
  q("REA.DED.SYL", 3,
    "Statements: Some trainers are managers. All managers are graduates.\nConclusion: Some trainers are graduates.\nDoes the conclusion follow?",
    "Yes, it definitely follows",
    { "No, it does not follow": "The trainers who are managers must be graduates.", "It follows only if all trainers are managers": "It's enough that some trainers are managers.", "Cannot be decided": "The overlap of trainers and managers settles it." },
    "The trainers who are managers are all graduates, so at least some trainers are graduates.",
    "Follow the overlap."),
  q("REA.DED.SYL", 3,
    "Statements: All laptops are devices. Some devices are faulty.\nConclusion: Some laptops are faulty.\nDoes the conclusion follow?",
    "No, it does not definitely follow",
    { "Yes, it definitely follows": "The faulty devices might all be non-laptops.", "Yes, all laptops are faulty": "Nothing says every device is faulty.", "Yes, no laptops are faulty": "That isn't certain either - it just isn't proven either way." },
    "The faulty devices could be phones or printers; nothing forces a laptop to be among them.",
    "Can you draw a diagram where the conclusion is false?"),
  q("REA.DED.SYL", 4,
    "Statements: No supervisors are interns. Some interns are graduates.\nConclusion: Some graduates are not supervisors.\nDoes the conclusion follow?",
    "Yes, it definitely follows",
    { "No, it does not follow": "The graduates who are interns can't be supervisors.", "Cannot be decided": "The interns who are graduates settle it.", "It follows only if all graduates are interns": "It's enough that some graduates are interns." },
    "Some graduates are interns, and no intern is a supervisor, so those graduates are not supervisors.",
    "Use the 'some' group and apply the 'no' rule to it."),
  q("REA.DED.SYL", 4,
    "Statements: All reports are documents. No documents are images.\nConclusions: I. No reports are images. II. Some documents are reports.\nWhich conclusion(s) follow?",
    "Both I and II follow",
    { "Only I follows": "II also follows: since all reports are documents, some documents are reports.", "Only II follows": "I also follows: reports are documents, and no document is an image.", "Neither follows": "Both can be proved from the statements." },
    "Reports ⊂ documents, documents and images don't overlap → no report is an image (I). And some documents are reports (II).",
    "Check each conclusion separately."),
  q("REA.DED.SYL", 5,
    "Statements: Some calls are complaints. Some complaints are escalations.\nConclusion: Some calls are escalations.\nDoes the conclusion follow?",
    "No, it does not definitely follow",
    { "Yes, it definitely follows": "Two 'some' statements don't force an overlap between calls and escalations.", "Yes, all calls are escalations": "Nothing says all calls are escalations.", "Yes, no calls are escalations": "That isn't proven either - it just isn't certain." },
    "The complaints that are calls and the complaints that are escalations could be different ones.",
    "Two 'some' statements never give a definite conclusion."),

  // ------------------------------------------------ REA: Blood relations
  q("REA.REL.BLOOD", 2,
    "Arjun is Kavya's brother. Kavya is Rohan's mother. How is Arjun related to Rohan?",
    "Uncle (mother's brother)",
    { Father: "Rohan's mother is Kavya; Arjun is her brother, not her husband.", Brother: "Arjun is a generation above Rohan.", Grandfather: "Arjun is Rohan's mother's brother - one generation up, not two." },
    "Arjun is the brother of Rohan's mother, so he is Rohan's maternal uncle.",
    "Go step by step from Rohan: mother → her brother."),
  q("REA.REL.BLOOD", 3,
    "Pointing to a photo, Sunil says, \"She is the daughter of my father's only son.\" How is the woman in the photo related to Sunil?",
    "Daughter",
    { Sister: "'My father's only son' is Sunil himself, so she is his daughter.", Niece: "A niece would be a sibling's daughter - Sunil has no brother.", Cousin: "A cousin would be the child of an uncle or aunt." },
    "Sunil's father's only son is Sunil. So she is Sunil's daughter.",
    "Work out who 'my father's only son' is first."),
  q("REA.REL.BLOOD", 3,
    "Neha's mother is the only daughter of Vijay. How is Vijay related to Neha?",
    "Grandfather",
    { Father: "Vijay is her mother's father - one generation further up.", Uncle: "An uncle is a parent's brother, not a parent's father.", "Father-in-law": "That would link through marriage, not through Neha's mother." },
    "Neha's mother's father is Neha's maternal grandfather.",
    "Draw the family tree: Vijay → his daughter → Neha."),
  q("REA.REL.BLOOD", 4,
    "A is the brother of B. B is the sister of C. C is the father of D. How is A related to D?",
    "Uncle",
    { Father: "C is D's father; A is C's sibling.", Grandfather: "A is in the same generation as C, D's father.", Cousin: "A cousin would be in D's generation." },
    "A, B and C are siblings. C is D's father, so A (a male sibling of C) is D's uncle.",
    "Put A, B and C in one generation, D below C."),
  q("REA.REL.BLOOD", 4,
    "Introducing a man, Meera says, \"His mother is the only daughter of my mother.\" How is Meera related to the man?",
    "Mother",
    { Sister: "The only daughter of Meera's mother is Meera herself - so she is his mother.", Aunt: "An aunt would be a sister of his mother - but Meera is the only daughter.", Grandmother: "His mother is Meera, one generation up, not two." },
    "The only daughter of Meera's mother is Meera, so the man's mother is Meera.",
    "Who is 'the only daughter of my mother'?"),
  q("REA.REL.BLOOD", 5,
    "P is the father of Q. Q is the daughter of R. R is the sister of S. S is the father of T. How is P related to T?",
    "Uncle (by marriage)",
    { Father: "S, not P, is T's father.", Grandfather: "P is in the same generation as S, T's father.", Brother: "P is a generation above T." },
    "P and R are Q's parents, so P is R's husband. R is S's sister, so P is S's brother-in-law - T's uncle by marriage.",
    "P and R share a child, so they are a couple."),

  // ------------------------------------------ REA: Statements and conclusions
  q("REA.DED.CONCLUSIONS", 3,
    "Statement: \"The company has announced that the office will remain closed on Friday for maintenance work.\"\nConclusions: I. No work will be done at the office on Friday. II. Maintenance work is needed at the office.\nWhich conclusion(s) follow?",
    "Only II follows",
    { "Only I follows": "Maintenance work WILL be done at the office on Friday, so I doesn't follow.", "Both I and II follow": "I goes too far - maintenance work is still work.", "Neither follows": "II follows: the closure is for maintenance work." },
    "The closure is for maintenance, so maintenance is needed (II). But work - the maintenance - will still happen (I fails).",
    "A conclusion must follow directly from the statement - no more, no less."),
  q("REA.DED.CONCLUSIONS", 4,
    "Statement: \"Only candidates with a typing speed of 35 words per minute or more will be shortlisted for the data-entry role.\"\nConclusions: I. Every candidate with 40 wpm will be selected. II. A candidate with 30 wpm will not be shortlisted.\nWhich conclusion(s) follow?",
    "Only II follows",
    { "Only I follows": "Meeting the minimum speed gets you considered, not selected.", "Both I and II follow": "I confuses 'eligible to be shortlisted' with 'selected'.", "Neither follows": "II follows directly: 30 wpm is below the minimum." },
    "35 wpm is necessary to be shortlisted, so 30 wpm won't be (II). It isn't enough to guarantee selection (I fails).",
    "'Only ... will' sets a minimum requirement, not a guarantee."),
];
