import Link from "next/link";

export const metadata = { title: "Terms of Service - VocalisAi" };

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="font-display text-lg font-bold text-ink-950">{title}</h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-slate-700">{children}</div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-6 py-12">
      <h1 className="font-display text-2xl font-bold text-ink-950">Terms of Service</h1>
      <p className="mt-1 text-sm text-slate-500">Last updated: September 15, 2026</p>

      <p className="mt-6 text-sm leading-relaxed text-slate-700">
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of VocalisAi (the
        &quot;Service&quot;), operated by Lakshay Dutt Tyagi (&quot;we&quot;, &quot;us&quot;, or
        &quot;our&quot;). By creating an account or using the Service, you agree to these Terms. If
        you do not agree, do not use the Service.
      </p>

      <Section title="1. Who can use VocalisAi">
        <p>
          You must be at least 18 years old to create an account. By using the Service, you
          confirm that you meet this requirement and that the information you provide during
          signup is accurate.
        </p>
      </Section>

      <Section title="2. What VocalisAi is (and isn't)">
        <p>
          VocalisAi is a self-directed voice, accent, and interview-skills practice tool. It
          gives you AI-generated feedback on your speech, practice questions, mock assessments,
          and coaching based on your own activity.
        </p>
        <p>
          VocalisAi does not guarantee any employment outcome, interview result, assessment
          score, or improvement in your speaking ability. Feedback is generated by third-party AI
          models and rule-based scoring, and may be incomplete or imperfect. You should use your
          own judgment, and where the stakes matter, a human reviewer's judgment, alongside
          anything VocalisAi tells you.
        </p>
        <p>
          VocalisAi does not evaluate or comment on your accent as being &quot;better&quot; or
          &quot;worse&quot;, and does not attempt to make you sound like a different nationality
          or background. Feedback is limited to clarity, pace, grammar, and similar communication
          fundamentals.
        </p>
      </Section>

      <Section title="3. Your account">
        <p>
          You are responsible for keeping your password confidential and for all activity that
          happens under your account. Tell us immediately at{" "}
          <a href="mailto:pcircuit@yahoo.com" className="text-brand-600 hover:underline">
            pcircuit@yahoo.com
          </a>{" "}
          if you believe your account has been accessed without your permission.
        </p>
      </Section>

      <Section title="4. Plans, usage limits, and the free tier">
        <p>
          VocalisAi is offered on paid subscription plans (Starter, Professional, Premium), each
          with its own monthly limits per feature - no plan, including paid plans, includes
          unlimited use of any feature. Limits reset at the start of each monthly billing period.
        </p>
        <p>
          A limited free sample is available to new accounts. The free sample is a one-time
          allowance, not a recurring monthly tier - once its limits are used, you will need a
          paid plan to continue using those features. We may change what is included in the free
          sample or paid plans at any time; changes apply going forward, not retroactively to a
          period you've already paid for.
        </p>
      </Section>

      <Section title="5. Payment and billing">
        <p>
          Paid plans are billed through Paddle.com, who acts as the merchant of record for your
          purchase. Paddle handles payment processing, invoicing, and any applicable sales tax,
          VAT, or GST for your country. We never receive or store your full card details -
          Paddle's own terms and privacy policy govern the payment transaction itself.
        </p>
        <p>
          Subscriptions renew automatically each billing period until you cancel. You can cancel
          at any time from your account; cancelling stops future renewals but does not refund the
          period already paid for (see our{" "}
          <Link href="/refund-policy" className="text-brand-600 hover:underline">
            Refund Policy
          </Link>
          ).
        </p>
      </Section>

      <Section title="6. Recording, proctoring, and your content">
        <p>
          Practicing on VocalisAi involves recording your voice, and mock assessments may use
          your device's camera and microphone to show integrity signals (for example, whether a
          face is visible, or whether you switched away from the assessment tab). These signals
          are shown to you and, for assessments an administrator has access to, to that
          administrator - they are informational flags, not automatic accusations of misconduct.
        </p>
        <p>
          You keep ownership of your recordings and responses. By submitting them, you give us
          permission to store, transcribe, and analyze them in order to provide the Service to
          you (see our{" "}
          <Link href="/privacy" className="text-brand-600 hover:underline">
            Privacy Policy
          </Link>{" "}
          for detail on how this data is handled).
        </p>
      </Section>

      <Section title="7. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>Use the Service for any unlawful purpose, or to harass or impersonate others.</li>
          <li>Attempt to bypass usage limits, access controls, or other candidates' data.</li>
          <li>Reverse engineer, scrape, or resell access to the Service.</li>
          <li>Upload content you don't have the right to share.</li>
        </ul>
        <p>We may suspend or terminate accounts that violate these Terms.</p>
      </Section>

      <Section title="8. Disclaimers and limitation of liability">
        <p>
          The Service is provided &quot;as is&quot;, without warranties of any kind. To the
          maximum extent permitted by law, we are not liable for indirect, incidental, or
          consequential damages arising from your use of the Service, and our total liability for
          any claim is limited to the amount you paid us in the 3 months before the claim arose.
        </p>
      </Section>

      <Section title="9. Changes to these Terms">
        <p>
          We may update these Terms from time to time. If we make a material change, we'll make
          a reasonable effort to notify you (for example, by email or an in-app notice). Continued
          use of the Service after a change takes effect means you accept the updated Terms.
        </p>
      </Section>

      <Section title="10. Governing law">
        <p>
          These Terms are governed by the laws of India, without regard to conflict-of-law
          principles. Any dispute arising from these Terms or the Service will be subject to the
          exclusive jurisdiction of the courts of India.
        </p>
      </Section>

      <Section title="11. Contact">
        <p>
          Questions about these Terms can be sent to{" "}
          <a href="mailto:pcircuit@yahoo.com" className="text-brand-600 hover:underline">
            pcircuit@yahoo.com
          </a>
          .
        </p>
      </Section>
    </div>
  );
}
